-- دليل الحسابات الكامل المستخرج من نظام غروب النايف (289 حساب)
create or replace function public.seed_full_kuwaiti_chart(p_company_id uuid)
returns void language plpgsql security definer set search_path to 'public' as $$
begin
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1', 'الأصول', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '11', 'الأصول الثابتة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1101', 'الأراضي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1102', 'المباني والتجهيزات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110201', 'مباني المركز الرئيسي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110202', 'مباني المخازن الرئيسية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1103', 'السيارات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110301', 'السيارة (1)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110302', 'السيارة (2)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1104', 'الأثاث والمفروشات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110401', 'الأثاث المكتبي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110402', 'الأجهزة الكهربائية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110403', 'أجهزة التكييف', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1105', 'الأجهزة والحاسبات الآلية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110501', 'أجهزة الطابعات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110502', 'أجهزة الحاسب الآلي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110503', 'ماكينات التصوير', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110504', 'برامج الحاسب الآلي (مرسملة)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1106', 'الديكورات والتحسينات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1107', 'مجمع إهلاك الأصول الثابتة (-)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110701', 'مجمع إهلاك المباني والتجهيزات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110702', 'مجمع إهلاك السيارات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110703', 'مجمع إهلاك الأثاث والمفروشات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '110704', 'مجمع إهلاك الأجهزة والحاسبات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1108', 'الآلات والمعدات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '12', 'الأصول غير الملموسة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1201', 'البرامج المحاسبية والتراخيص', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1202', 'العلامة التجارية والشهرة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1203', 'أصول غير ملموسة أخرى', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1209', 'مجمع إطفاء الأصول غير الملموسة (-)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1210', 'براءة اختراع', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '13', 'مشروعات تحت التنفيذ', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1301', 'مشروعات تحت التنفيذ (1)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1302', 'مشروعات تحت التنفيذ (2)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '14', 'الاستثمارات طويلة الأجل', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1401', 'استثمارات في شركات شقيقة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1402', 'استثمارات عقارية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '15', 'الأصول المتداولة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1501', 'النقدية بالصندوق', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150101', 'نقدية صندوق المركز الرئيسي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150102', 'نقدية صندوق فرع ........', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1502', 'النقدية بالبنوك', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150201', 'بنك الخليج', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150202', 'بيت التمويل الكويتي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150203', 'البنك الوطني', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150204', 'ودائع تحت الطلب', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150205', 'بنك برقان', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150206', 'البنك الأهلي الكويتي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150207', 'بنك الكويت الدولي (KIB)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150208', 'بنك بوبيان', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1503', 'شيكات تحت التحصيل', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1504', 'خطابات الضمان', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150401', 'خطاب ضمان ابتدائي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150402', 'خطاب ضمان نهائي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1505', 'الاعتمادات المستندية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150501', 'اعتماد مستندي صادر', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150502', 'اعتماد مستندي وارد', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1506', 'العملاء', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150601', 'ذمم جمعية الفنطاس التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150602', 'ذمم جمعية العدان والقصور التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150603', 'ذمم جمعية المنقف التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150604', 'ذمم جمعية الفحيحيل التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150605', 'ذمم جمعية الرقة التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150606', 'ذمم جمعية هدية التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150607', 'ذمم جمعية العقيلة التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150608', 'ذمم جمعية الصباحية التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150609', 'ذمم جمعية الظهر التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150610', 'ذمم جمعية صباح الاحمد التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150611', 'ذمم جمعية الأحمدي التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150612', 'ذمم جمعية جابر العلي التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150613', 'ذمم جمعية علي صباح السالم التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150614', 'ذمم جمعية غرب عبدالله المبارك التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150615', 'ذمم جمعية  صباح السالم التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150616', 'ذمم جمعية الوفره الزراعيه', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150617', 'ذمم جمعية ابوفطيره التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150618', 'ذمم جمعية بيان التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150619', 'ذمم جمعية الشعب التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150620', 'ذمم جمعية الدعيه التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150621', 'ذمم جمعية صباح الناصر التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150622', 'ذمم جمعية اشبيلية التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150623', 'ذمم سوق العايش المركزي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150624', 'ذمم سوق النادر المركزي', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150625', 'ذمم جمعية مبارك الكبير والقرين التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150626', 'ذمم جمعية سلوي التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150627', 'ذمم جمعية ابوحليفه التعاونية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150628', 'ذمم عملاء نقديه', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150629', 'ذمم عملاء جمعيات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150630', 'ذمم عملاء محليين', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150631', 'ذمم عملاء خارجيين', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150632', 'مخصص ديون مشكوك في تحصيلها (-)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1507', 'المخزون', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150701', 'مخزون البضاعة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150702', 'مخزون قطع الغيار والمستلزمات', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150703', 'بضاعة في الطريق (تحويلات بين الفروع)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150704', 'مخصص هبوط أسعار المخزون (-)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1508', 'المدينون', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150801', 'شركة / .....................', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150802', 'شركة / .....................', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1509', 'العهد', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150901', 'عهدة الموظف / (1)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '150902', 'عهدة الموظف / (2)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1510', 'ذمم الموظفين (سُلف)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151001', 'سلفة موظف (1)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151002', 'سلفة موظف (2)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151003', 'سلفة موظف (3)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1511', 'الأرصدة المدينة الأخرى', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151101', 'ضريبة أرباح تجارية وصناعية مدفوعة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151102', 'ضريبة مخصومة من المنبع', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151103', 'تأمينات لدى الغير', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151104', 'إيرادات مستحقة', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151105', 'مصروفات مدفوعة مقدماً', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151106', 'ضريبة القيمة المضافة - مدخلات (قابلة للخصم)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151107', 'أصول متداولة أخرى', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1512', 'أوراق القبض', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151201', 'أوراق قبض برسم التحصيل', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151202', 'أوراق قبض', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '1513', 'الاستثمارات قصيرة الأجل', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '151301', 'أوراق مالية قصيرة الأجل', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2', 'الخصوم وحقوق الملكية', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '21', 'الخصوم المتداولة', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2101', 'الدائنون', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210101', 'الدائن / (1)', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210102', 'الدائن / (2)', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2102', 'الموردون', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210201', 'ذمم الموردين المحليين', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210202', 'ذمم موردين آخرين', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210203', 'ذمم مورد — شركة السماني', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2103', 'أوراق الدفع', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2104', 'مصروفات مستحقة', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210401', 'رواتب وأجور مستحقة', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210402', 'مصروف / ...............', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2105', 'الأرصدة الدائنة الأخرى', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210501', 'التأمينات الاجتماعية مستحقة', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210502', 'ضريبة القيمة المضافة - مخرجات (مستحقة)', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210503', 'ضريبة القيمة المضافة - الرصيد المستحق للسداد', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210504', 'ضرائب مستحقة أخرى', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210505', 'تأمينات محتجزة للغير', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210506', 'إيرادات مقدمة (مقبوضة مقدماً)', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210507', 'مخصص الزكاة مستحق', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210508', 'دعم العمالة الوطنية مستحق', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210509', 'أرباح موزّعة مستحقة الدفع', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2106', 'المخصصات قصيرة الأجل', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210601', 'مخصص مكافأة نهاية الخدمة - جزء متداول', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210602', 'مخصص الزكاة المستحقة', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210603', 'مخصص ضريبة الدخل المستحقة', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '210604', 'مخصص دعم العمالة الوطنية المستحق', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2107', 'البنوك دائنة (سحب على المكشوف)', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '22', 'الخصوم طويلة الأجل', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2201', 'القروض طويلة الأجل', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '220101', 'قرض البنك التجاري', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '220102', 'قرض / .............', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2202', 'مخصص مكافأة نهاية الخدمة (طويل الأجل)', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2203', 'سندات قرض مصدرة', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2204', 'أوراق دفع طويلة الأجل', 'liability', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '23', 'حقوق الملكية', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2301', 'رأس المال', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230101', 'رأس المال المدفوع - الشريك (أ)', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230102', 'رأس المال المدفوع - الشريك (ب)', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2302', 'جاري الشركاء', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230201', 'جاري الشريك (1)', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230202', 'جاري الشريك (2)', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2303', 'الاحتياطيات', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230301', 'الاحتياطي القانوني', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230302', 'الاحتياطي العام / الاختياري', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2304', 'الأرباح (الخسائر) المرحّلة', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230401', 'أرباح مرحّلة من أعوام سابقة', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2305', 'صافي أرباح (خسائر) العام الحالي [مُرحّل من ملخص الدخل]', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2306', 'مسحوبات الشركاء (-) [شركة أشخاص]', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230601', 'مسحوبات الشريك', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '2307', 'توزيعات أرباح معلنة (-) [شركة أموال]', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230701', 'توزيعات أرباح الشريك (أ)', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '230702', 'توزيعات أرباح الشريك (ب)', 'equity', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3', 'المصروفات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '31', 'تكلفة المبيعات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3101', 'مخزون أول المدة [جرد دوري]', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3102', 'المشتريات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310201', 'مشتريات آجلة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310202', 'مشتريات نقدية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310203', 'مشتريات خارجية (استيراد)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310204', 'مردودات المشتريات (-)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310205', 'خصم مكتسب (-)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310206', 'مسموحات المشتريات (-)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3103', 'مصروفات المشتريات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310301', 'مصروفات نقل المشتريات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310302', 'عمولات على المشتريات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310303', 'رسوم جمركية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310304', 'مصاريف تأمين المشتريات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3104', 'مخزون آخر المدة (-) [جرد دوري]', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3105', 'تكلفة البضاعة المباعة [جرد مستمر]', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '310501', 'عجز وتلف المخزون (ضمن التكلفة)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3106', 'تأمين المشتريات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '32', 'المصروفات التسويقية والبيعية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3201', 'الدعاية والإعلان', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '320101', 'دعاية بالصحف والمجلات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '320102', 'دعاية بوسائل الإعلام', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3202', 'رواتب وعمولات مندوبي المبيعات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '320201', 'رواتب نقدية للمندوبين', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '320202', 'مزايا عينية للمندوبين', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '320203', 'عمولات مندوبي المبيعات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3203', 'هدايا للعملاء', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3204', 'مصاريف نقل وتوزيع المبيعات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3205', 'مصاريف تشغيل وصيانة سيارات التوزيع', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '320501', 'وقود سيارات التوزيع', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '320502', 'صيانة سيارات التوزيع', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3206', 'مصاريف إيجار أرفف واستندات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '33', 'المصروفات الإدارية والعمومية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3301', 'مصروفات إدارية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330101', 'رواتب وأجور', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330102', 'حوافز ومكافآت', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330103', 'مصاريف وعمولات بنكية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330104', 'مصاريف مناقصات وممارسات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330105', 'مصاريف نثرية متنوعة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330106', 'التأمينات الاجتماعية (حصة جهة العمل)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330107', 'مصاريف انتقالات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330108', 'مصاريف إيجارات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330109', 'مصاريف سفر', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330110', 'مصاريف هاتف وبريد وإنترنت', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330111', 'مصاريف كهرباء ومياه', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330112', 'مصاريف مطبوعات وأدوات كتابية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330113', 'رسوم وتراخيص حكومية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330114', 'مصاريف صيانة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330115', 'أتعاب مهنية واستشارات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330116', 'مصاريف إدارية أخرى', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330117', 'مصاريف تأسيس', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330118', 'تأمين سيارات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330119', 'ضيافة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330120', 'مصروفات أدوات تعقيم', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330121', 'أدوات مكتبية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330122', 'صيانة سيارات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3302', 'مصروف الإهلاك والإطفاء', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330201', 'مصروف إهلاك المباني', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330202', 'مصروف إهلاك السيارات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330203', 'مصروف إهلاك الأثاث والمفروشات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330204', 'مصروف إهلاك الأجهزة والحاسبات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330205', 'مصروف إطفاء الأصول غير الملموسة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3303', 'المخصصات (بخلاف الإهلاك)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330301', 'تكوين مخصص الديون المشكوك فيها', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330302', 'تكوين مخصص هبوط أسعار المخزون', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330303', 'تكوين مخصص مكافأة نهاية الخدمة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '330304', 'فروق الجرد (رقابية)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '34', 'مصروفات وخسائر أخرى', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3401', 'مصروفات وخسائر أخرى متنوعة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '340101', 'ديون معدومة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '340102', 'خسائر بيع أوراق مالية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '340103', 'تعويضات وغرامات', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '340104', 'خسائر فروق عملة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '340105', 'مصروفات سنوات سابقة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '340106', 'خسائر رأسمالية (بيع أصول)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '35', 'المصروفات التمويلية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3501', 'أعباء وفوائد تمويلية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '350101', 'فوائد بنكية مدينة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '350102', 'مصروفات وعمولات تمويلية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '36', 'الضرائب والزكاة (بعد صافي الربح)', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '3601', 'الزكاة والضرائب', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '360101', 'الزكاة', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '360102', 'دعم العمالة الوطنية', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '360103', 'حصة مؤسسة الكويت للتقدم العلمي', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '360104', 'ضريبة الدخل', 'expense', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '4', 'الإيرادات', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '41', 'إيرادات النشاط', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '4101', 'المبيعات المحلية', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '410101', 'المبيعات', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '410102', 'مردودات المبيعات (-)', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '410103', 'خصم مسموح به (-)', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '410104', 'بضاعة مجانية (-)', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '4102', 'المبيعات الخارجية (التصدير)', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '410201', 'مبيعات التصدير', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '4103', 'إيرادات خدمات', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '410301', 'إيرادات نقل وتوصيل', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '410302', 'إيرادات عمولات موردين (Listing/Rebates)', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '42', 'الإيرادات الأخرى', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '4201', 'إيرادات وأرباح أخرى', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420101', 'فوائد دائنة', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420102', 'رد مخصصات انتفى الغرض منها', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420103', 'ديون سبق إعدامها (محصّلة)', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420104', 'أرباح بيع أوراق مالية', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420105', 'عمولات مكتسبة', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420106', 'تعويضات وغرامات مكتسبة', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420107', 'أرباح رأسمالية (بيع أصول)', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420108', 'أرباح فروق عملة', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420109', 'إيرادات متنوعة', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '420110', 'إيرادات إيجار', 'revenue', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '5', 'الحسابات الختامية والنظامية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '51', 'حسابات الإقفال', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '5101', 'ملخص الدخل (المتاجرة والأرباح والخسائر)', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '510101', 'ملخص الدخل', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '52', 'حسابات الافتتاح', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '5201', 'حساب الميزانية الافتتاحية', 'asset', true) on conflict (company_id, code) do nothing;
  insert into chart_of_accounts (company_id, code, name_ar, account_type, is_system) values (p_company_id, '520101', 'رصيد افتتاحي (Opening Balance Equity)', 'asset', true) on conflict (company_id, code) do nothing;
end;
$$;